---
title: "Specificities"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Specificities}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Packages and methods used

In this package, we decided to use `GDAL` and `GRASS` software for their functionalities and computational speed. 
In the same way, we used Cloud Optimized GeoTIFFs (COG) to download only the data needed for all climatic files. This technique can done with the `gdal_translate` function and the `/vsicurl` virtual file system. 
In R itself, `terra` and `stars` packages help to handle and visualize Tiff files as R object.

## Computing time

Comparison with 3 different areas : New Caledonia, French Guiana and Madagascar.

For all area, resolution is set to 1km. Others parameters don't change computing time.

| Area          | transform_shp_country_extent | get_env_variable | get_chelsa_current | merge_files | get_chelsa_future |
| :-----------: | :--------------------------: | :--------------: | :----------------: | :---------: | :---------------: |
| Madagascar    | 2min                         | 15min            | 34min              | 6min        | 1h15min           |
| New Caledonia | 2min                         | 5min             | 9min               | 8min        | 47min             |
| French Guiana | 2min                         | 3min             | 6min               | 2min        | 25min             |

## Output size

| Area          | layer's size | number of cells |
| :-----------: | :----------: | :-------------: |
| Madagascar    | 1673 x 875   | 1.463.875       |
| New Caledonia | 689 x 1921   | 1.323.569       |
| French Guiana | 444 x 445    | 197.580         |

## Type of output

Each output is a multilayer Tiff file with `-32768` as NoData value. All values are in `Int16` for optimizing space on disk.

